nexus:
  image: sonatype/nexus3:3.71.0
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8081
  storage:
    size: 10Gi
    storageClassName: gp3-csi

postgresql:
  image: postgres:15
  database: nexus
  username: nexus
  password: nexuspassword
  storage:
    size: 10Gi
    storageClassName: gp3-csi
