apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: {{ .Values.nexus.service.type }}
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: {{ .Values.nexus.service.port }}
      targetPort: 8081
