apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  storageClassName: {{ .Values.nexus.storageClassName }}
  capacity:
    storage: {{ .Values.nexus.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /nexus-data
