apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  storageClassName: {{ .Values.postgresql.storage.storageClassName }}
  capacity:
    storage: {{ .Values.postgresql.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /postgresql-data
